name: train-model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install pandas
          pip3 install numpy
          pip3 install matplotlib
          pip3 install tensorflow
          pip3 install jovian
          pip3 install torch
          pip3 install seaborn
          pip3 install torchvision
          pip3 install sklearn
          python pytorch.py
          python evaluation.py
          RUN 
